import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.CIDADE).count<[{ count: number }]>(
    "* as count"
  );
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const cidadesToInsert = cidadesDeSaoPaulo.map((cidade) => ({ nome: cidade }));
  await knex(ETableNames.CIDADE).insert(cidadesToInsert);
};

const cidadesParte1 = [
  "Adamantina",
  "Adolfo",
  "Aguaí",
  "Águas da Prata",
  "Águas de Lindóia",
  "Águas de Santa Bárbara",
  "Águas de São Pedro",
  "Agudos",
  "Alambari",
  "Alfredo Marcondes",
  "Altair",
  "Altinópolis",
  "Alto Alegre",
  "Alumínio",
  "Álvares Florence",
  "Álvares Machado",
  "Álvaro de Carvalho",
  "Alvinlândia",
  "Americana",
  "Américo Brasiliense",
  "Américo de Campos",
  "Amparo",
  "Analândia",
  "Andradina",
  "Angatuba",
  "Anhembi",
  "Anhumas",
  "Aparecida",
];

const cidadesParte2 = [
  "Aparecida d'Oeste",
  "Apiaí",
  "Araçariguama",
  "Araçatuba",
  "Araçoiaba da Serra",
  "Aramina",
  "Arandu",
  "Arapeí",
  "Araraquara",
  "Araras",
  "Arco-Íris",
  "Arealva",
  "Areias",
  "Areiópolis",
  "Ariranha",
  "Artur Nogueira",
  "Arujá",
  "Aspásia",
  "Assis",
  "Atibaia",
  "Auriflama",
  "Avaí",
  "Avanhandava",
  "Avaré",
  "Bady Bassitt",
  "Balbinos",
  "Bálsamo",
];

const cidadesParte3 = [
  "Bananal",
  "Barão de Antonina",
  "Barbosa",
  "Bariri",
  "Barra Bonita",
  "Barra do Chapéu",
  "Barra do Turvo",
  "Barretos",
  "Barrinha",
  "Barueri",
  "Bastos",
  "Batatais",
  "Bauru",
  "Bebedouro",
  "Bento de Abreu",
  "Bernardino de Campos",
  "Bertioga",
  "Bilac",
  "Birigui",
  "Biritiba-Mirim",
];

const cidadesParte4 = [
  "Boa Esperança do Sul",
  "Bocaina",
  "Bofete",
  "Boituva",
  "Bom Jesus dos Perdões",
  "Bom Sucesso de Itararé",
  "Borá",
  "Boracéia",
  "Borborema",
  "Borebi",
  "Botucatu",
  "Bragança Paulista",
  "Braúna",
  "Brejo Alegre",
  "Brodowski",
  "Brotas",
  "Buri",
  "Buritama",
  "Buritizal",
  "Cabrália Paulista",
  "Cabreúva",
];

const cidadesParte5 = [
  "Caçapava",
  "Cachoeira Paulista",
  "Caconde",
  "Cafelândia",
  "Caiabu",
  "Caieiras",
  "Caiuá",
  "Cajamar",
  "Cajati",
  "Cajobi",
  "Cajuru",
  "Campina do Monte Alegre",
  "Campinas",
  "Campo Limpo Paulista",
  "Campos do Jordão",
  "Catanduva",
  "Catiguá",
  "Cedral",
  "Cerqueira César",
  "Cerquilho",
];

const cidadesParte6 = [
  "Cesário Lange",
  "Charqueada",
  "Chavantes",
  "Clementina",
  "Colina",
  "Colômbia",
  "Conchal",
  "Conchas",
  "Cordeirópolis",
  "Coroados",
  "Coronel Macedo",
  "Corumbataí",
  "Cosmópolis",
  "Cosmorama",
  "Cotia",
  "Cravinhos",
  "Cristais Paulista",
  "Cruzália",
  "Cruzeiro",
  "Cubatão",
];

const cidadesParte7 = [
  "Cunha",
  "Descalvado",
  "Diadema",
  "Dirce Reis",
  "Divinolândia",
  "Dobrada",
  "Dois Córregos",
  "Dolcinópolis",
  "Dourado",
  "Dracena",
  "Duartina",
  "Dumont",
  "Echaporã",
  "Eldorado",
  "Elias Fausto",
  "Elisiário",
  "Embaúba",
  "Embu",
  "Embu-Guaçu",
  "Emilianópolis",
];

const cidadesParte8 = [
  "Engenheiro Coelho",
  "Espírito Santo do Pinhal",
  "Espírito Santo do Turvo",
  "Estiva Gerbi",
  "Estrela d'Oeste",
  "Estrela do Norte",
  "Euclides da Cunha Paulista",
  "Fartura",
  "Fernando Prestes",
  "Fernandópolis",
  "Fernão",
  "Ferraz de Vasconcelos",
  "Flora Rica",
  "Floreal",
  "Florínia",
  "Flórida Paulista",
  "Franca",
  "Francisco Morato",
];

const cidadesParte9 = [
  "Franco da Rocha",
  "Gabriel Monteiro",
  "Gália",
  "Garça",
  "Gastão Vidigal",
  "Gavião Peixoto",
  "General Salgado",
  "Getulina",
  "Glicério",
  "Guaiçara",
  "Guaimbê",
  "Guaíra",
  "Guapiaçu",
  "Guapiara",
  "Guará",
  "Guaraçaí",
  "Guaraci",
  "Guarani d'Oeste",
  "Guarantã",
  "Guararapes",
];

const cidadesParte10 = [
  "Guararema",
  "Guaratinguetá",
  "Guareí",
  "Guariba",
  "Guarujá",
  "Guarulhos",
  "Guatapará",
  "Guzolândia",
  "Herculândia",
  "Holambra",
  "Hortolândia",
  "Iacanga",
  "Iacri",
  "Iaras",
  "Ibaté",
  "Iporanga",
  "Ipuã",
  "Iracemápolis",
  "Irapuã",
  "Irapuru",
];

const cidadesDeSaoPaulo = [
  ...cidadesParte1,
  ...cidadesParte2,
  ...cidadesParte3,
  ...cidadesParte4,
  ...cidadesParte5,
  ...cidadesParte6,
  ...cidadesParte7,
  ...cidadesParte8,
  ...cidadesParte9,
  ...cidadesParte10,
];
